# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(795, 711)
        Dialog.setMinimumSize(QtCore.QSize(500, 600))
        Dialog.setMaximumSize(QtCore.QSize(1920, 1080))
        Dialog.setStyleSheet("background-color: rgb(30, 30, 30);")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.tabWidget.setStyleSheet("QTabWidget::tab-bar {\n"
"border: 1px solid red;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"  background: rgb(70, 83, 66);\n"
"  color: rgb(201, 216, 197);\n"
"  padding: 10px;\n"
" }\n"
"\n"
" QTabBar::tab:selected {\n"
"  background: rgb(52, 62, 49);\n"
" }\n"
"")
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.HuffmanComp = QtWidgets.QWidget()
        self.HuffmanComp.setObjectName("HuffmanComp")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.HuffmanComp)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.HuffmanComp)
        self.label.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.origHuffmanText = QtWidgets.QTextEdit(self.HuffmanComp)
        self.origHuffmanText.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 9pt \"Inter\";")
        self.origHuffmanText.setObjectName("origHuffmanText")
        self.horizontalLayout_8.addWidget(self.origHuffmanText)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.chooseFile = QtWidgets.QPushButton(self.HuffmanComp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseFile.sizePolicy().hasHeightForWidth())
        self.chooseFile.setSizePolicy(sizePolicy)
        self.chooseFile.setMinimumSize(QtCore.QSize(250, 50))
        self.chooseFile.setMaximumSize(QtCore.QSize(300, 16777215))
        self.chooseFile.setAcceptDrops(True)
        self.chooseFile.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chooseFile.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.chooseFile.setObjectName("chooseFile")
        self.verticalLayout_6.addWidget(self.chooseFile, 0, QtCore.Qt.AlignHCenter)
        self.chosenFile = QtWidgets.QLabel(self.HuffmanComp)
        self.chosenFile.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.chosenFile.setObjectName("chosenFile")
        self.verticalLayout_6.addWidget(self.chosenFile)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.ButtonEnter = QtWidgets.QPushButton(self.HuffmanComp)
        self.ButtonEnter.setMinimumSize(QtCore.QSize(250, 50))
        self.ButtonEnter.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ButtonEnter.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.ButtonEnter.setObjectName("ButtonEnter")
        self.verticalLayout_12.addWidget(self.ButtonEnter, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem3)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_38 = QtWidgets.QLabel(self.HuffmanComp)
        self.label_38.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_38.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_22.addWidget(self.label_38)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem4)
        self.compTimeHuf = QtWidgets.QTextBrowser(self.HuffmanComp)
        self.compTimeHuf.setMaximumSize(QtCore.QSize(100, 20))
        self.compTimeHuf.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.compTimeHuf.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.compTimeHuf.setObjectName("compTimeHuf")
        self.horizontalLayout_22.addWidget(self.compTimeHuf)
        self.verticalLayout_12.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_39 = QtWidgets.QLabel(self.HuffmanComp)
        self.label_39.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_23.addWidget(self.label_39)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem5)
        self.OrigSizeHuf = QtWidgets.QTextBrowser(self.HuffmanComp)
        self.OrigSizeHuf.setMaximumSize(QtCore.QSize(100, 20))
        self.OrigSizeHuf.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.OrigSizeHuf.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.OrigSizeHuf.setObjectName("OrigSizeHuf")
        self.horizontalLayout_23.addWidget(self.OrigSizeHuf)
        self.verticalLayout_12.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_40 = QtWidgets.QLabel(self.HuffmanComp)
        self.label_40.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_24.addWidget(self.label_40)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem6)
        self.CompSizeHuf = QtWidgets.QTextBrowser(self.HuffmanComp)
        self.CompSizeHuf.setMaximumSize(QtCore.QSize(100, 20))
        self.CompSizeHuf.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.CompSizeHuf.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompSizeHuf.setObjectName("CompSizeHuf")
        self.horizontalLayout_24.addWidget(self.CompSizeHuf)
        self.verticalLayout_12.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_41 = QtWidgets.QLabel(self.HuffmanComp)
        self.label_41.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_25.addWidget(self.label_41)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem7)
        self.CompPercHuf = QtWidgets.QTextBrowser(self.HuffmanComp)
        self.CompPercHuf.setMaximumSize(QtCore.QSize(100, 20))
        self.CompPercHuf.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.CompPercHuf.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompPercHuf.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompPercHuf.setObjectName("CompPercHuf")
        self.horizontalLayout_25.addWidget(self.CompPercHuf)
        self.verticalLayout_12.addLayout(self.horizontalLayout_25)
        self.verticalLayout_6.addLayout(self.verticalLayout_12)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.status = QtWidgets.QLabel(self.HuffmanComp)
        self.status.setMinimumSize(QtCore.QSize(0, 30))
        self.status.setMaximumSize(QtCore.QSize(3000, 30))
        self.status.setStyleSheet("color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.status.setText("")
        self.status.setObjectName("status")
        self.verticalLayout_6.addWidget(self.status)
        self.tabWidget.addTab(self.HuffmanComp, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.button_decompress = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_decompress.sizePolicy().hasHeightForWidth())
        self.button_decompress.setSizePolicy(sizePolicy)
        self.button_decompress.setMinimumSize(QtCore.QSize(0, 50))
        self.button_decompress.setMaximumSize(QtCore.QSize(300, 50))
        self.button_decompress.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.button_decompress.setObjectName("button_decompress")
        self.gridLayout_5.addWidget(self.button_decompress, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 3, 0, 1, 1)
        self.button_files_4 = QtWidgets.QPushButton(self.tab_2)
        self.button_files_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_files_4.sizePolicy().hasHeightForWidth())
        self.button_files_4.setSizePolicy(sizePolicy)
        self.button_files_4.setMinimumSize(QtCore.QSize(300, 100))
        self.button_files_4.setMaximumSize(QtCore.QSize(300, 100))
        self.button_files_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.button_files_4.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.button_files_4.setObjectName("button_files_4")
        self.gridLayout_5.addWidget(self.button_files_4, 1, 0, 1, 1)
        self.uploaded_files_4 = QtWidgets.QLabel(self.tab_2)
        self.uploaded_files_4.setMinimumSize(QtCore.QSize(0, 30))
        self.uploaded_files_4.setMaximumSize(QtCore.QSize(300, 16777215))
        self.uploaded_files_4.setStyleSheet("border-color: rgb(78, 139, 119);\n"
"color: rgb(201, 216, 197);\n"
"border: 1px solid  rgb(78, 139, 119);\n"
"font: 75 9pt \"Inter\";\n"
"border-radius:3px;")
        self.uploaded_files_4.setText("")
        self.uploaded_files_4.setObjectName("uploaded_files_4")
        self.gridLayout_5.addWidget(self.uploaded_files_4, 4, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 62, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem9, 5, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 62, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem10, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 61, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem11, 2, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 61, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem12, 7, 0, 1, 1)
        self.status_4 = QtWidgets.QLabel(self.tab_2)
        self.status_4.setMinimumSize(QtCore.QSize(0, 30))
        self.status_4.setMaximumSize(QtCore.QSize(294, 30))
        self.status_4.setStyleSheet("color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.status_4.setText("")
        self.status_4.setObjectName("status_4")
        self.gridLayout_5.addWidget(self.status_4, 8, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_7.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.OriginalText = QtWidgets.QTextEdit(self.tab_4)
        self.OriginalText.setMaximumSize(QtCore.QSize(16777215, 5000))
        self.OriginalText.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 9pt \"Inter\";")
        self.OriginalText.setObjectName("OriginalText")
        self.verticalLayout.addWidget(self.OriginalText)
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 50000))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 12pt \"Inter\";")
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.parametri = QtWidgets.QVBoxLayout()
        self.parametri.setObjectName("parametri")
        self.buffer = QtWidgets.QHBoxLayout()
        self.buffer.setObjectName("buffer")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_6.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_6.setObjectName("label_6")
        self.buffer.addWidget(self.label_6)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buffer.addItem(spacerItem13)
        self.WindowSize = QtWidgets.QSpinBox(self.tab_4)
        self.WindowSize.setMinimumSize(QtCore.QSize(100, 30))
        self.WindowSize.setStyleSheet("QSpinBox\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QSpinBox:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.WindowSize.setWrapping(False)
        self.WindowSize.setFrame(True)
        self.WindowSize.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.WindowSize.setMaximum(9999)
        self.WindowSize.setProperty("value", 1)
        self.WindowSize.setObjectName("WindowSize")
        self.buffer.addWidget(self.WindowSize)
        self.parametri.addLayout(self.buffer)
        self.razmerokna = QtWidgets.QHBoxLayout()
        self.razmerokna.setObjectName("razmerokna")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_9.setObjectName("label_9")
        self.razmerokna.addWidget(self.label_9)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.razmerokna.addItem(spacerItem14)
        self.BufferSize = QtWidgets.QSpinBox(self.tab_4)
        self.BufferSize.setMinimumSize(QtCore.QSize(100, 30))
        self.BufferSize.setStyleSheet("QSpinBox\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QSpinBox:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.BufferSize.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.BufferSize.setMaximum(9999)
        self.BufferSize.setProperty("value", 1)
        self.BufferSize.setObjectName("BufferSize")
        self.razmerokna.addWidget(self.BufferSize)
        self.parametri.addLayout(self.razmerokna)
        self.verticalLayout.addLayout(self.parametri)
        self.pushButton = QtWidgets.QPushButton(self.tab_4)
        self.pushButton.setMinimumSize(QtCore.QSize(250, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(3000, 16777215))
        self.pushButton.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)
        self.compressedResult = QtWidgets.QPlainTextEdit(self.tab_4)
        self.compressedResult.setEnabled(True)
        self.compressedResult.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 9pt \"Inter\";")
        self.compressedResult.setReadOnly(True)
        self.compressedResult.setPlainText("")
        self.compressedResult.setObjectName("compressedResult")
        self.verticalLayout.addWidget(self.compressedResult)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem15)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem16)
        self.CompressionTime = QtWidgets.QTextBrowser(self.tab_4)
        self.CompressionTime.setMaximumSize(QtCore.QSize(100, 20))
        self.CompressionTime.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.CompressionTime.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompressionTime.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompressionTime.setObjectName("CompressionTime")
        self.horizontalLayout_4.addWidget(self.CompressionTime)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem17)
        self.originalTextSize = QtWidgets.QTextBrowser(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.originalTextSize.sizePolicy().hasHeightForWidth())
        self.originalTextSize.setSizePolicy(sizePolicy)
        self.originalTextSize.setMaximumSize(QtCore.QSize(100, 20))
        self.originalTextSize.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.originalTextSize.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.originalTextSize.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.originalTextSize.setObjectName("originalTextSize")
        self.horizontalLayout_2.addWidget(self.originalTextSize)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem18)
        self.compressedTextSize = QtWidgets.QTextBrowser(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compressedTextSize.sizePolicy().hasHeightForWidth())
        self.compressedTextSize.setSizePolicy(sizePolicy)
        self.compressedTextSize.setMaximumSize(QtCore.QSize(100, 20))
        self.compressedTextSize.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.compressedTextSize.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.compressedTextSize.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.compressedTextSize.setReadOnly(True)
        self.compressedTextSize.setObjectName("compressedTextSize")
        self.horizontalLayout.addWidget(self.compressedTextSize)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem19)
        self.CompressionPercentage = QtWidgets.QTextBrowser(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CompressionPercentage.sizePolicy().hasHeightForWidth())
        self.CompressionPercentage.setSizePolicy(sizePolicy)
        self.CompressionPercentage.setMaximumSize(QtCore.QSize(100, 20))
        self.CompressionPercentage.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.CompressionPercentage.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompressionPercentage.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompressionPercentage.setObjectName("CompressionPercentage")
        self.horizontalLayout_3.addWidget(self.CompressionPercentage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_4, "")
        self.lz77decompression = QtWidgets.QWidget()
        self.lz77decompression.setObjectName("lz77decompression")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.lz77decompression)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_14 = QtWidgets.QLabel(self.lz77decompression)
        self.label_14.setStyleSheet("border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.compressedText = QtWidgets.QTextEdit(self.lz77decompression)
        self.compressedText.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 9pt \"Inter\";")
        self.compressedText.setObjectName("compressedText")
        self.verticalLayout_3.addWidget(self.compressedText)
        self.pushButton_2 = QtWidgets.QPushButton(self.lz77decompression)
        self.pushButton_2.setMinimumSize(QtCore.QSize(250, 50))
        self.pushButton_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_2.setToolTipDuration(-2)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignHCenter)
        self.decompressedText = QtWidgets.QTextEdit(self.lz77decompression)
        self.decompressedText.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 9pt \"Inter\";")
        self.decompressedText.setObjectName("decompressedText")
        self.verticalLayout_3.addWidget(self.decompressedText)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_17 = QtWidgets.QLabel(self.lz77decompression)
        self.label_17.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem20)
        self.decompressionTimeStat = QtWidgets.QTextBrowser(self.lz77decompression)
        self.decompressionTimeStat.setMaximumSize(QtCore.QSize(100, 20))
        self.decompressionTimeStat.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.decompressionTimeStat.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.decompressionTimeStat.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.decompressionTimeStat.setObjectName("decompressionTimeStat")
        self.horizontalLayout_7.addWidget(self.decompressionTimeStat)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_16 = QtWidgets.QLabel(self.lz77decompression)
        self.label_16.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_6.addWidget(self.label_16)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem21)
        self.CompressedSizeStat = QtWidgets.QTextBrowser(self.lz77decompression)
        self.CompressedSizeStat.setMaximumSize(QtCore.QSize(100, 20))
        self.CompressedSizeStat.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.CompressedSizeStat.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompressedSizeStat.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompressedSizeStat.setObjectName("CompressedSizeStat")
        self.horizontalLayout_6.addWidget(self.CompressedSizeStat)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_15 = QtWidgets.QLabel(self.lz77decompression)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_15.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem22)
        self.DecompressedSizeStat = QtWidgets.QTextBrowser(self.lz77decompression)
        self.DecompressedSizeStat.setMaximumSize(QtCore.QSize(100, 20))
        self.DecompressedSizeStat.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.DecompressedSizeStat.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DecompressedSizeStat.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DecompressedSizeStat.setObjectName("DecompressedSizeStat")
        self.horizontalLayout_5.addWidget(self.DecompressedSizeStat)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.lz77decompression, "")
        self.DeflateComp = QtWidgets.QWidget()
        self.DeflateComp.setObjectName("DeflateComp")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.DeflateComp)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem23)
        self.label_34 = QtWidgets.QLabel(self.DeflateComp)
        self.label_34.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_34.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_34.setObjectName("label_34")
        self.verticalLayout_10.addWidget(self.label_34)
        self.OriginalText_3 = QtWidgets.QTextEdit(self.DeflateComp)
        self.OriginalText_3.setMaximumSize(QtCore.QSize(16777215, 300))
        self.OriginalText_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 9pt \"Inter\";")
        self.OriginalText_3.setObjectName("OriginalText_3")
        self.verticalLayout_10.addWidget(self.OriginalText_3)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem24)
        self.chooseFile_3 = QtWidgets.QPushButton(self.DeflateComp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseFile_3.sizePolicy().hasHeightForWidth())
        self.chooseFile_3.setSizePolicy(sizePolicy)
        self.chooseFile_3.setMinimumSize(QtCore.QSize(250, 50))
        self.chooseFile_3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.chooseFile_3.setAcceptDrops(True)
        self.chooseFile_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chooseFile_3.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.chooseFile_3.setObjectName("chooseFile_3")
        self.verticalLayout_10.addWidget(self.chooseFile_3, 0, QtCore.Qt.AlignHCenter)
        self.chosenFile_3 = QtWidgets.QLabel(self.DeflateComp)
        self.chosenFile_3.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.chosenFile_3.setObjectName("chosenFile_3")
        self.verticalLayout_10.addWidget(self.chosenFile_3)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem25)
        self.pushButton_5 = QtWidgets.QPushButton(self.DeflateComp)
        self.pushButton_5.setMinimumSize(QtCore.QSize(250, 50))
        self.pushButton_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_10.addWidget(self.pushButton_5, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_33 = QtWidgets.QLabel(self.DeflateComp)
        self.label_33.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_33.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_18.addWidget(self.label_33)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem26)
        self.compTime = QtWidgets.QTextBrowser(self.DeflateComp)
        self.compTime.setMaximumSize(QtCore.QSize(100, 20))
        self.compTime.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.compTime.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.compTime.setObjectName("compTime")
        self.horizontalLayout_18.addWidget(self.compTime)
        self.verticalLayout_11.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_35 = QtWidgets.QLabel(self.DeflateComp)
        self.label_35.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_19.addWidget(self.label_35)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem27)
        self.OrigSize = QtWidgets.QTextBrowser(self.DeflateComp)
        self.OrigSize.setMaximumSize(QtCore.QSize(100, 20))
        self.OrigSize.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.OrigSize.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.OrigSize.setObjectName("OrigSize")
        self.horizontalLayout_19.addWidget(self.OrigSize)
        self.verticalLayout_11.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_36 = QtWidgets.QLabel(self.DeflateComp)
        self.label_36.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_20.addWidget(self.label_36)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem28)
        self.CompSize = QtWidgets.QTextBrowser(self.DeflateComp)
        self.CompSize.setMaximumSize(QtCore.QSize(100, 20))
        self.CompSize.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.CompSize.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompSize.setObjectName("CompSize")
        self.horizontalLayout_20.addWidget(self.CompSize)
        self.verticalLayout_11.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_37 = QtWidgets.QLabel(self.DeflateComp)
        self.label_37.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_21.addWidget(self.label_37)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem29)
        self.CompPerc = QtWidgets.QTextBrowser(self.DeflateComp)
        self.CompPerc.setMaximumSize(QtCore.QSize(100, 20))
        self.CompPerc.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.CompPerc.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompPerc.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompPerc.setObjectName("CompPerc")
        self.horizontalLayout_21.addWidget(self.CompPerc)
        self.verticalLayout_11.addLayout(self.horizontalLayout_21)
        self.verticalLayout_10.addLayout(self.verticalLayout_11)
        self.tabWidget.addTab(self.DeflateComp, "")
        self.DeflateDecomp = QtWidgets.QWidget()
        self.DeflateDecomp.setObjectName("DeflateDecomp")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.DeflateDecomp)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem30 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem30)
        self.button_files_5 = QtWidgets.QPushButton(self.DeflateDecomp)
        self.button_files_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_files_5.sizePolicy().hasHeightForWidth())
        self.button_files_5.setSizePolicy(sizePolicy)
        self.button_files_5.setMinimumSize(QtCore.QSize(300, 100))
        self.button_files_5.setMaximumSize(QtCore.QSize(300, 100))
        self.button_files_5.setSizeIncrement(QtCore.QSize(0, 0))
        self.button_files_5.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.button_files_5.setObjectName("button_files_5")
        self.verticalLayout_5.addWidget(self.button_files_5, 0, QtCore.Qt.AlignHCenter)
        spacerItem31 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem31)
        self.label_18 = QtWidgets.QLabel(self.DeflateDecomp)
        self.label_18.setMinimumSize(QtCore.QSize(300, 0))
        self.label_18.setMaximumSize(QtCore.QSize(300, 20))
        self.label_18.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_5.addWidget(self.label_18, 0, QtCore.Qt.AlignHCenter)
        self.uploaded_files_5 = QtWidgets.QLabel(self.DeflateDecomp)
        self.uploaded_files_5.setMinimumSize(QtCore.QSize(300, 30))
        self.uploaded_files_5.setMaximumSize(QtCore.QSize(300, 50))
        self.uploaded_files_5.setStyleSheet("border-color: rgb(78, 139, 119);\n"
"color: rgb(201, 216, 197);\n"
"border: 1px solid  rgb(78, 139, 119);\n"
"font: 75 9pt \"Inter\";\n"
"border-radius:3px;")
        self.uploaded_files_5.setText("")
        self.uploaded_files_5.setObjectName("uploaded_files_5")
        self.verticalLayout_5.addWidget(self.uploaded_files_5, 0, QtCore.Qt.AlignHCenter)
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem32)
        self.button_decompress_2 = QtWidgets.QPushButton(self.DeflateDecomp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_decompress_2.sizePolicy().hasHeightForWidth())
        self.button_decompress_2.setSizePolicy(sizePolicy)
        self.button_decompress_2.setMinimumSize(QtCore.QSize(300, 50))
        self.button_decompress_2.setMaximumSize(QtCore.QSize(300, 50))
        self.button_decompress_2.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.button_decompress_2.setObjectName("button_decompress_2")
        self.verticalLayout_5.addWidget(self.button_decompress_2, 0, QtCore.Qt.AlignHCenter)
        spacerItem33 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem33)
        self.status_5 = QtWidgets.QLabel(self.DeflateDecomp)
        self.status_5.setMinimumSize(QtCore.QSize(300, 30))
        self.status_5.setMaximumSize(QtCore.QSize(300, 30))
        self.status_5.setStyleSheet("color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.status_5.setText("")
        self.status_5.setObjectName("status_5")
        self.verticalLayout_5.addWidget(self.status_5, 0, QtCore.Qt.AlignHCenter)
        self.tabWidget.addTab(self.DeflateDecomp, "")
        self.Brotli = QtWidgets.QWidget()
        self.Brotli.setAutoFillBackground(False)
        self.Brotli.setStyleSheet("QTabBar::tab {\n"
"  background: gray;\n"
"  color: white;\n"
"  padding: 10px;\n"
" }\n"
"\n"
" QTabBar::tab:selected {\n"
"  background: lightgray;\n"
" }")
        self.Brotli.setObjectName("Brotli")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Brotli)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem34 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem34)
        self.label_2 = QtWidgets.QLabel(self.Brotli)
        self.label_2.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.origTextBrotli = QtWidgets.QTextEdit(self.Brotli)
        self.origTextBrotli.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 9pt \"Inter\";")
        self.origTextBrotli.setObjectName("origTextBrotli")
        self.horizontalLayout_9.addWidget(self.origTextBrotli)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        spacerItem35 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem35)
        self.ChooseFileBrotli = QtWidgets.QPushButton(self.Brotli)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChooseFileBrotli.sizePolicy().hasHeightForWidth())
        self.ChooseFileBrotli.setSizePolicy(sizePolicy)
        self.ChooseFileBrotli.setMinimumSize(QtCore.QSize(250, 50))
        self.ChooseFileBrotli.setMaximumSize(QtCore.QSize(300, 16777215))
        self.ChooseFileBrotli.setAcceptDrops(True)
        self.ChooseFileBrotli.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ChooseFileBrotli.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.ChooseFileBrotli.setObjectName("ChooseFileBrotli")
        self.verticalLayout_7.addWidget(self.ChooseFileBrotli, 0, QtCore.Qt.AlignHCenter)
        self.ChosenFileBrotli = QtWidgets.QLabel(self.Brotli)
        self.ChosenFileBrotli.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.ChosenFileBrotli.setObjectName("ChosenFileBrotli")
        self.verticalLayout_7.addWidget(self.ChosenFileBrotli)
        spacerItem36 = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem36)
        self.ButtonEnterBrotli = QtWidgets.QPushButton(self.Brotli)
        self.ButtonEnterBrotli.setMinimumSize(QtCore.QSize(250, 50))
        self.ButtonEnterBrotli.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ButtonEnterBrotli.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.ButtonEnterBrotli.setObjectName("ButtonEnterBrotli")
        self.verticalLayout_7.addWidget(self.ButtonEnterBrotli, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        spacerItem37 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem37)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_42 = QtWidgets.QLabel(self.Brotli)
        self.label_42.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_42.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_26.addWidget(self.label_42)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem38)
        self.compTimeBrotli = QtWidgets.QTextBrowser(self.Brotli)
        self.compTimeBrotli.setMaximumSize(QtCore.QSize(100, 20))
        self.compTimeBrotli.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.compTimeBrotli.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.compTimeBrotli.setObjectName("compTimeBrotli")
        self.horizontalLayout_26.addWidget(self.compTimeBrotli)
        self.verticalLayout_13.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_43 = QtWidgets.QLabel(self.Brotli)
        self.label_43.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_27.addWidget(self.label_43)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem39)
        self.OrigSizeBrotli = QtWidgets.QTextBrowser(self.Brotli)
        self.OrigSizeBrotli.setMaximumSize(QtCore.QSize(100, 20))
        self.OrigSizeBrotli.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.OrigSizeBrotli.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.OrigSizeBrotli.setObjectName("OrigSizeBrotli")
        self.horizontalLayout_27.addWidget(self.OrigSizeBrotli)
        self.verticalLayout_13.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_44 = QtWidgets.QLabel(self.Brotli)
        self.label_44.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_28.addWidget(self.label_44)
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem40)
        self.CompSizeBrotli = QtWidgets.QTextBrowser(self.Brotli)
        self.CompSizeBrotli.setMaximumSize(QtCore.QSize(100, 20))
        self.CompSizeBrotli.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.CompSizeBrotli.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompSizeBrotli.setObjectName("CompSizeBrotli")
        self.horizontalLayout_28.addWidget(self.CompSizeBrotli)
        self.verticalLayout_13.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_45 = QtWidgets.QLabel(self.Brotli)
        self.label_45.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_29.addWidget(self.label_45)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem41)
        self.CompPercBrotli = QtWidgets.QTextBrowser(self.Brotli)
        self.CompPercBrotli.setMaximumSize(QtCore.QSize(100, 20))
        self.CompPercBrotli.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.CompPercBrotli.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompPercBrotli.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompPercBrotli.setObjectName("CompPercBrotli")
        self.horizontalLayout_29.addWidget(self.CompPercBrotli)
        self.verticalLayout_13.addLayout(self.horizontalLayout_29)
        self.verticalLayout_7.addLayout(self.verticalLayout_13)
        spacerItem42 = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem42)
        self.status_2 = QtWidgets.QLabel(self.Brotli)
        self.status_2.setMinimumSize(QtCore.QSize(0, 30))
        self.status_2.setMaximumSize(QtCore.QSize(3000, 30))
        self.status_2.setStyleSheet("color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.status_2.setText("")
        self.status_2.setObjectName("status_2")
        self.verticalLayout_7.addWidget(self.status_2)
        self.tabWidget.addTab(self.Brotli, "")
        self.BrotliDecomp = QtWidgets.QWidget()
        self.BrotliDecomp.setMinimumSize(QtCore.QSize(777, 0))
        self.BrotliDecomp.setObjectName("BrotliDecomp")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.BrotliDecomp)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem43 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem43, 3, 1, 1, 1)
        spacerItem44 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem44, 6, 1, 1, 1)
        spacerItem45 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem45, 9, 1, 1, 1)
        self.uploadedFilesBrotli = QtWidgets.QLabel(self.BrotliDecomp)
        self.uploadedFilesBrotli.setMinimumSize(QtCore.QSize(0, 30))
        self.uploadedFilesBrotli.setMaximumSize(QtCore.QSize(300, 30))
        self.uploadedFilesBrotli.setStyleSheet("border-color: rgb(78, 139, 119);\n"
"color: rgb(201, 216, 197);\n"
"border: 1px solid  rgb(78, 139, 119);\n"
"font: 75 9pt \"Inter\";\n"
"border-radius:3px;")
        self.uploadedFilesBrotli.setText("")
        self.uploadedFilesBrotli.setObjectName("uploadedFilesBrotli")
        self.gridLayout_4.addWidget(self.uploadedFilesBrotli, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.BrotliDecomp)
        self.label_5.setMaximumSize(QtCore.QSize(300, 30))
        self.label_5.setStyleSheet("\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 4, 1, 1, 1)
        self.buttonDecompBrotli = QtWidgets.QPushButton(self.BrotliDecomp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDecompBrotli.sizePolicy().hasHeightForWidth())
        self.buttonDecompBrotli.setSizePolicy(sizePolicy)
        self.buttonDecompBrotli.setMinimumSize(QtCore.QSize(0, 50))
        self.buttonDecompBrotli.setMaximumSize(QtCore.QSize(300, 50))
        self.buttonDecompBrotli.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.buttonDecompBrotli.setObjectName("buttonDecompBrotli")
        self.gridLayout_4.addWidget(self.buttonDecompBrotli, 8, 1, 1, 1)
        self.statusBrotli = QtWidgets.QLabel(self.BrotliDecomp)
        self.statusBrotli.setMinimumSize(QtCore.QSize(300, 30))
        self.statusBrotli.setMaximumSize(QtCore.QSize(300, 30))
        self.statusBrotli.setStyleSheet("color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.statusBrotli.setText("")
        self.statusBrotli.setObjectName("statusBrotli")
        self.gridLayout_4.addWidget(self.statusBrotli, 10, 1, 1, 1)
        self.ChooseFilesBrotli = QtWidgets.QPushButton(self.BrotliDecomp)
        self.ChooseFilesBrotli.setEnabled(True)
        self.ChooseFilesBrotli.setMinimumSize(QtCore.QSize(300, 100))
        self.ChooseFilesBrotli.setMaximumSize(QtCore.QSize(300, 100))
        self.ChooseFilesBrotli.setSizeIncrement(QtCore.QSize(0, 0))
        self.ChooseFilesBrotli.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.ChooseFilesBrotli.setObjectName("ChooseFilesBrotli")
        self.gridLayout_4.addWidget(self.ChooseFilesBrotli, 2, 1, 1, 1)
        spacerItem46 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem46, 0, 1, 1, 1)
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem47, 5, 0, 1, 1)
        spacerItem48 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem48, 5, 2, 1, 1)
        self.tabWidget.addTab(self.BrotliDecomp, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tabWidget.setToolTip(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.HuffmanComp.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("Dialog", "Введите текст или выберите файл для сжатия:"))
        self.chooseFile.setText(_translate("Dialog", "Выберите файл"))
        self.chosenFile.setText(_translate("Dialog", "Выбранный файл:"))
        self.ButtonEnter.setText(_translate("Dialog", "Ввод"))
        self.label_38.setText(_translate("Dialog", "Время выполнения сжатия:"))
        self.label_39.setText(_translate("Dialog", "Размер изначального текста:"))
        self.label_40.setText(_translate("Dialog", "Размер сжатого текста:"))
        self.label_41.setText(_translate("Dialog", "Процент сжатия: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.HuffmanComp), _translate("Dialog", "Huffman"))
        self.button_decompress.setText(_translate("Dialog", "Ввод"))
        self.label_4.setText(_translate("Dialog", "Выбранный файл:"))
        self.button_files_4.setText(_translate("Dialog", "Выбрать файл"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Huffman декомпрессия"))
        self.label_7.setText(_translate("Dialog", "Введите текст:"))
        self.label_8.setText(_translate("Dialog", "Параметры"))
        self.label_6.setText(_translate("Dialog", "Размер скользящего окна:"))
        self.label_9.setText(_translate("Dialog", "Буфер"))
        self.pushButton.setText(_translate("Dialog", "Ввод"))
        self.label_13.setText(_translate("Dialog", "Время выполнения сжатия:"))
        self.label_11.setText(_translate("Dialog", "Размер изначального текста:"))
        self.label_10.setText(_translate("Dialog", "Размер сжатого текста:"))
        self.label_12.setText(_translate("Dialog", "Процент сжатия: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "LZ77"))
        self.label_14.setText(_translate("Dialog", "Введите закодированную последовательность:"))
        self.pushButton_2.setText(_translate("Dialog", "Ввод"))
        self.label_17.setText(_translate("Dialog", "Время выполнения декомпрессии:"))
        self.label_16.setText(_translate("Dialog", "Размер входных данных:"))
        self.label_15.setText(_translate("Dialog", "Размер оригинального текста:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.lz77decompression), _translate("Dialog", "LZ77 декомпрессия"))
        self.label_34.setText(_translate("Dialog", "Введите текст или выберите файл для сжатия:"))
        self.chooseFile_3.setText(_translate("Dialog", "Выберите файл"))
        self.chosenFile_3.setText(_translate("Dialog", "Выбранный файл:"))
        self.pushButton_5.setText(_translate("Dialog", "Ввод"))
        self.label_33.setText(_translate("Dialog", "Время выполнения сжатия:"))
        self.label_35.setText(_translate("Dialog", "Размер изначального текста:"))
        self.label_36.setText(_translate("Dialog", "Размер сжатого текста:"))
        self.label_37.setText(_translate("Dialog", "Процент сжатия: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DeflateComp), _translate("Dialog", "Deflate"))
        self.button_files_5.setText(_translate("Dialog", "Выбрать файл"))
        self.label_18.setText(_translate("Dialog", "Выбранный файл:"))
        self.button_decompress_2.setText(_translate("Dialog", "Ввод"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DeflateDecomp), _translate("Dialog", "Deflate декомпрессия"))
        self.label_2.setText(_translate("Dialog", "Введите текст или выберите файл для сжатия:"))
        self.ChooseFileBrotli.setText(_translate("Dialog", "Выберите файл"))
        self.ChosenFileBrotli.setText(_translate("Dialog", "Выбранный файл:"))
        self.ButtonEnterBrotli.setText(_translate("Dialog", "Ввод"))
        self.label_42.setText(_translate("Dialog", "Время выполнения сжатия:"))
        self.label_43.setText(_translate("Dialog", "Размер изначального текста:"))
        self.label_44.setText(_translate("Dialog", "Размер сжатого текста:"))
        self.label_45.setText(_translate("Dialog", "Процент сжатия: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Brotli), _translate("Dialog", "Brotli компрессия"))
        self.label_5.setText(_translate("Dialog", "Выбранный файл:"))
        self.buttonDecompBrotli.setText(_translate("Dialog", "Ввод"))
        self.ChooseFilesBrotli.setText(_translate("Dialog", "Выбрать файл"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.BrotliDecomp), _translate("Dialog", "Brotli декомпрессия"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
