# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(795, 711)
        Dialog.setMinimumSize(QtCore.QSize(500, 600))
        Dialog.setMaximumSize(QtCore.QSize(1920, 1080))
        Dialog.setStyleSheet("background-color: rgb(30, 30, 30);")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.tabWidget.setStyleSheet("QTabWidget::tab-bar {\n"
"border: 1px solid red;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"  background: rgb(70, 83, 66);\n"
"  color: rgb(201, 216, 197);\n"
"  padding: 10px;\n"
" }\n"
"\n"
" QTabBar::tab:selected {\n"
"  background: rgb(52, 62, 49);\n"
" }\n"
"")
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.HuffmanComp = QtWidgets.QWidget()
        self.HuffmanComp.setObjectName("HuffmanComp")
        self.gridLayout = QtWidgets.QGridLayout(self.HuffmanComp)
        self.gridLayout.setObjectName("gridLayout")
        self.status = QtWidgets.QLabel(self.HuffmanComp)
        self.status.setMinimumSize(QtCore.QSize(0, 30))
        self.status.setMaximumSize(QtCore.QSize(3000, 30))
        self.status.setStyleSheet("color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.status.setText("")
        self.status.setObjectName("status")
        self.gridLayout.addWidget(self.status, 13, 0, 1, 1)
        self.chosenFile = QtWidgets.QLabel(self.HuffmanComp)
        self.chosenFile.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.chosenFile.setObjectName("chosenFile")
        self.gridLayout.addWidget(self.chosenFile, 9, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 10, 0, 1, 1)
        self.ButtonEnter = QtWidgets.QPushButton(self.HuffmanComp)
        self.ButtonEnter.setMinimumSize(QtCore.QSize(250, 50))
        self.ButtonEnter.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ButtonEnter.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.ButtonEnter.setObjectName("ButtonEnter")
        self.gridLayout.addWidget(self.ButtonEnter, 11, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 12, 0, 1, 1)
        self.chooseFile = QtWidgets.QPushButton(self.HuffmanComp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseFile.sizePolicy().hasHeightForWidth())
        self.chooseFile.setSizePolicy(sizePolicy)
        self.chooseFile.setMinimumSize(QtCore.QSize(250, 50))
        self.chooseFile.setMaximumSize(QtCore.QSize(300, 16777215))
        self.chooseFile.setAcceptDrops(True)
        self.chooseFile.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chooseFile.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.chooseFile.setObjectName("chooseFile")
        self.gridLayout.addWidget(self.chooseFile, 8, 0, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.HuffmanComp)
        self.label.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.origHuffmanText = QtWidgets.QTextEdit(self.HuffmanComp)
        self.origHuffmanText.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 9pt \"Inter\";")
        self.origHuffmanText.setObjectName("origHuffmanText")
        self.horizontalLayout_8.addWidget(self.origHuffmanText)
        self.gridLayout.addLayout(self.horizontalLayout_8, 6, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.HuffmanComp, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.button_decompress = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_decompress.sizePolicy().hasHeightForWidth())
        self.button_decompress.setSizePolicy(sizePolicy)
        self.button_decompress.setMinimumSize(QtCore.QSize(0, 50))
        self.button_decompress.setMaximumSize(QtCore.QSize(300, 50))
        self.button_decompress.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.button_decompress.setObjectName("button_decompress")
        self.gridLayout_5.addWidget(self.button_decompress, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 3, 0, 1, 1)
        self.button_files_4 = QtWidgets.QPushButton(self.tab_2)
        self.button_files_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_files_4.sizePolicy().hasHeightForWidth())
        self.button_files_4.setSizePolicy(sizePolicy)
        self.button_files_4.setMinimumSize(QtCore.QSize(300, 100))
        self.button_files_4.setMaximumSize(QtCore.QSize(300, 100))
        self.button_files_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.button_files_4.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.button_files_4.setObjectName("button_files_4")
        self.gridLayout_5.addWidget(self.button_files_4, 1, 0, 1, 1)
        self.uploaded_files_4 = QtWidgets.QLabel(self.tab_2)
        self.uploaded_files_4.setMinimumSize(QtCore.QSize(0, 30))
        self.uploaded_files_4.setMaximumSize(QtCore.QSize(300, 16777215))
        self.uploaded_files_4.setStyleSheet("border-color: rgb(78, 139, 119);\n"
"color: rgb(201, 216, 197);\n"
"border: 1px solid  rgb(78, 139, 119);\n"
"font: 75 9pt \"Inter\";\n"
"border-radius:3px;")
        self.uploaded_files_4.setText("")
        self.uploaded_files_4.setObjectName("uploaded_files_4")
        self.gridLayout_5.addWidget(self.uploaded_files_4, 4, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 62, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem4, 5, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 62, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem5, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 61, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 2, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 61, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem7, 7, 0, 1, 1)
        self.status_4 = QtWidgets.QLabel(self.tab_2)
        self.status_4.setMinimumSize(QtCore.QSize(0, 30))
        self.status_4.setMaximumSize(QtCore.QSize(294, 30))
        self.status_4.setStyleSheet("color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.status_4.setText("")
        self.status_4.setObjectName("status_4")
        self.gridLayout_5.addWidget(self.status_4, 8, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_7.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.OriginalText = QtWidgets.QTextEdit(self.tab_4)
        self.OriginalText.setMaximumSize(QtCore.QSize(16777215, 5000))
        self.OriginalText.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 9pt \"Inter\";")
        self.OriginalText.setObjectName("OriginalText")
        self.verticalLayout.addWidget(self.OriginalText)
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 50000))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 12pt \"Inter\";")
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.parametri = QtWidgets.QVBoxLayout()
        self.parametri.setObjectName("parametri")
        self.buffer = QtWidgets.QHBoxLayout()
        self.buffer.setObjectName("buffer")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_6.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_6.setObjectName("label_6")
        self.buffer.addWidget(self.label_6)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buffer.addItem(spacerItem8)
        self.WindowSize = QtWidgets.QSpinBox(self.tab_4)
        self.WindowSize.setMinimumSize(QtCore.QSize(100, 30))
        self.WindowSize.setStyleSheet("QSpinBox\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QSpinBox:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.WindowSize.setWrapping(False)
        self.WindowSize.setFrame(True)
        self.WindowSize.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.WindowSize.setMaximum(9999)
        self.WindowSize.setProperty("value", 1)
        self.WindowSize.setObjectName("WindowSize")
        self.buffer.addWidget(self.WindowSize)
        self.parametri.addLayout(self.buffer)
        self.razmerokna = QtWidgets.QHBoxLayout()
        self.razmerokna.setObjectName("razmerokna")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_9.setObjectName("label_9")
        self.razmerokna.addWidget(self.label_9)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.razmerokna.addItem(spacerItem9)
        self.BufferSize = QtWidgets.QSpinBox(self.tab_4)
        self.BufferSize.setMinimumSize(QtCore.QSize(100, 30))
        self.BufferSize.setStyleSheet("QSpinBox\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QSpinBox:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.BufferSize.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.BufferSize.setMaximum(9999)
        self.BufferSize.setProperty("value", 1)
        self.BufferSize.setObjectName("BufferSize")
        self.razmerokna.addWidget(self.BufferSize)
        self.parametri.addLayout(self.razmerokna)
        self.verticalLayout.addLayout(self.parametri)
        self.pushButton = QtWidgets.QPushButton(self.tab_4)
        self.pushButton.setMinimumSize(QtCore.QSize(250, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(3000, 16777215))
        self.pushButton.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)
        self.compressedResult = QtWidgets.QPlainTextEdit(self.tab_4)
        self.compressedResult.setEnabled(True)
        self.compressedResult.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 9pt \"Inter\";")
        self.compressedResult.setReadOnly(True)
        self.compressedResult.setPlainText("")
        self.compressedResult.setObjectName("compressedResult")
        self.verticalLayout.addWidget(self.compressedResult)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.CompressionTime = QtWidgets.QTextBrowser(self.tab_4)
        self.CompressionTime.setMaximumSize(QtCore.QSize(100, 20))
        self.CompressionTime.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.CompressionTime.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompressionTime.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompressionTime.setObjectName("CompressionTime")
        self.horizontalLayout_4.addWidget(self.CompressionTime)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.originalTextSize = QtWidgets.QTextBrowser(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.originalTextSize.sizePolicy().hasHeightForWidth())
        self.originalTextSize.setSizePolicy(sizePolicy)
        self.originalTextSize.setMaximumSize(QtCore.QSize(100, 20))
        self.originalTextSize.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.originalTextSize.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.originalTextSize.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.originalTextSize.setObjectName("originalTextSize")
        self.horizontalLayout_2.addWidget(self.originalTextSize)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.compressedTextSize = QtWidgets.QTextBrowser(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compressedTextSize.sizePolicy().hasHeightForWidth())
        self.compressedTextSize.setSizePolicy(sizePolicy)
        self.compressedTextSize.setMaximumSize(QtCore.QSize(100, 20))
        self.compressedTextSize.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.compressedTextSize.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.compressedTextSize.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.compressedTextSize.setReadOnly(True)
        self.compressedTextSize.setObjectName("compressedTextSize")
        self.horizontalLayout.addWidget(self.compressedTextSize)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem14)
        self.CompressionPercentage = QtWidgets.QTextBrowser(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CompressionPercentage.sizePolicy().hasHeightForWidth())
        self.CompressionPercentage.setSizePolicy(sizePolicy)
        self.CompressionPercentage.setMaximumSize(QtCore.QSize(100, 20))
        self.CompressionPercentage.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.CompressionPercentage.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompressionPercentage.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompressionPercentage.setObjectName("CompressionPercentage")
        self.horizontalLayout_3.addWidget(self.CompressionPercentage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_4, "")
        self.lz77decompression = QtWidgets.QWidget()
        self.lz77decompression.setObjectName("lz77decompression")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.lz77decompression)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_14 = QtWidgets.QLabel(self.lz77decompression)
        self.label_14.setStyleSheet("border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.compressedText = QtWidgets.QTextEdit(self.lz77decompression)
        self.compressedText.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 9pt \"Inter\";")
        self.compressedText.setObjectName("compressedText")
        self.verticalLayout_3.addWidget(self.compressedText)
        self.pushButton_2 = QtWidgets.QPushButton(self.lz77decompression)
        self.pushButton_2.setMinimumSize(QtCore.QSize(250, 50))
        self.pushButton_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignHCenter)
        self.decompressedText = QtWidgets.QTextEdit(self.lz77decompression)
        self.decompressedText.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 9pt \"Inter\";")
        self.decompressedText.setObjectName("decompressedText")
        self.verticalLayout_3.addWidget(self.decompressedText)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_17 = QtWidgets.QLabel(self.lz77decompression)
        self.label_17.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem15)
        self.decompressionTimeStat = QtWidgets.QTextBrowser(self.lz77decompression)
        self.decompressionTimeStat.setMaximumSize(QtCore.QSize(100, 20))
        self.decompressionTimeStat.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.decompressionTimeStat.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.decompressionTimeStat.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.decompressionTimeStat.setObjectName("decompressionTimeStat")
        self.horizontalLayout_7.addWidget(self.decompressionTimeStat)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_16 = QtWidgets.QLabel(self.lz77decompression)
        self.label_16.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_6.addWidget(self.label_16)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem16)
        self.CompressedSizeStat = QtWidgets.QTextBrowser(self.lz77decompression)
        self.CompressedSizeStat.setMaximumSize(QtCore.QSize(100, 20))
        self.CompressedSizeStat.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.CompressedSizeStat.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompressedSizeStat.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompressedSizeStat.setObjectName("CompressedSizeStat")
        self.horizontalLayout_6.addWidget(self.CompressedSizeStat)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_15 = QtWidgets.QLabel(self.lz77decompression)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_15.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem17)
        self.DecompressedSizeStat = QtWidgets.QTextBrowser(self.lz77decompression)
        self.DecompressedSizeStat.setMaximumSize(QtCore.QSize(100, 20))
        self.DecompressedSizeStat.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.DecompressedSizeStat.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DecompressedSizeStat.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DecompressedSizeStat.setObjectName("DecompressedSizeStat")
        self.horizontalLayout_5.addWidget(self.DecompressedSizeStat)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.lz77decompression, "")
        self.DeflateComp = QtWidgets.QWidget()
        self.DeflateComp.setObjectName("DeflateComp")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.DeflateComp)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem18)
        self.label_34 = QtWidgets.QLabel(self.DeflateComp)
        self.label_34.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_34.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_34.setObjectName("label_34")
        self.verticalLayout_10.addWidget(self.label_34)
        self.OriginalText_3 = QtWidgets.QTextEdit(self.DeflateComp)
        self.OriginalText_3.setMaximumSize(QtCore.QSize(16777215, 300))
        self.OriginalText_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 9pt \"Inter\";")
        self.OriginalText_3.setObjectName("OriginalText_3")
        self.verticalLayout_10.addWidget(self.OriginalText_3)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem19)
        self.chooseFile_3 = QtWidgets.QPushButton(self.DeflateComp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseFile_3.sizePolicy().hasHeightForWidth())
        self.chooseFile_3.setSizePolicy(sizePolicy)
        self.chooseFile_3.setMinimumSize(QtCore.QSize(250, 50))
        self.chooseFile_3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.chooseFile_3.setAcceptDrops(True)
        self.chooseFile_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chooseFile_3.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.chooseFile_3.setObjectName("chooseFile_3")
        self.verticalLayout_10.addWidget(self.chooseFile_3, 0, QtCore.Qt.AlignHCenter)
        self.chosenFile_3 = QtWidgets.QLabel(self.DeflateComp)
        self.chosenFile_3.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.chosenFile_3.setObjectName("chosenFile_3")
        self.verticalLayout_10.addWidget(self.chosenFile_3)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem20)
        self.pushButton_5 = QtWidgets.QPushButton(self.DeflateComp)
        self.pushButton_5.setMinimumSize(QtCore.QSize(250, 50))
        self.pushButton_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_10.addWidget(self.pushButton_5, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_33 = QtWidgets.QLabel(self.DeflateComp)
        self.label_33.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_33.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_18.addWidget(self.label_33)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem21)
        self.compTime = QtWidgets.QTextBrowser(self.DeflateComp)
        self.compTime.setMaximumSize(QtCore.QSize(100, 20))
        self.compTime.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.compTime.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.compTime.setObjectName("compTime")
        self.horizontalLayout_18.addWidget(self.compTime)
        self.verticalLayout_11.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_35 = QtWidgets.QLabel(self.DeflateComp)
        self.label_35.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_19.addWidget(self.label_35)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem22)
        self.OrigSize = QtWidgets.QTextBrowser(self.DeflateComp)
        self.OrigSize.setMaximumSize(QtCore.QSize(100, 20))
        self.OrigSize.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.OrigSize.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.OrigSize.setObjectName("OrigSize")
        self.horizontalLayout_19.addWidget(self.OrigSize)
        self.verticalLayout_11.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_36 = QtWidgets.QLabel(self.DeflateComp)
        self.label_36.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_20.addWidget(self.label_36)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem23)
        self.CompSize = QtWidgets.QTextBrowser(self.DeflateComp)
        self.CompSize.setMaximumSize(QtCore.QSize(100, 20))
        self.CompSize.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.CompSize.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompSize.setObjectName("CompSize")
        self.horizontalLayout_20.addWidget(self.CompSize)
        self.verticalLayout_11.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_37 = QtWidgets.QLabel(self.DeflateComp)
        self.label_37.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_21.addWidget(self.label_37)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem24)
        self.CompPerc = QtWidgets.QTextBrowser(self.DeflateComp)
        self.CompPerc.setMaximumSize(QtCore.QSize(100, 20))
        self.CompPerc.setStyleSheet("QTextBrowser\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser:hover\n"
"{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.CompPerc.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompPerc.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CompPerc.setObjectName("CompPerc")
        self.horizontalLayout_21.addWidget(self.CompPerc)
        self.verticalLayout_11.addLayout(self.horizontalLayout_21)
        self.verticalLayout_10.addLayout(self.verticalLayout_11)
        self.tabWidget.addTab(self.DeflateComp, "")
        self.DeflateDecomp = QtWidgets.QWidget()
        self.DeflateDecomp.setObjectName("DeflateDecomp")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.DeflateDecomp)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem25)
        self.button_files_5 = QtWidgets.QPushButton(self.DeflateDecomp)
        self.button_files_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_files_5.sizePolicy().hasHeightForWidth())
        self.button_files_5.setSizePolicy(sizePolicy)
        self.button_files_5.setMinimumSize(QtCore.QSize(300, 100))
        self.button_files_5.setMaximumSize(QtCore.QSize(300, 100))
        self.button_files_5.setSizeIncrement(QtCore.QSize(0, 0))
        self.button_files_5.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.button_files_5.setObjectName("button_files_5")
        self.verticalLayout_5.addWidget(self.button_files_5, 0, QtCore.Qt.AlignHCenter)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem26)
        self.label_18 = QtWidgets.QLabel(self.DeflateDecomp)
        self.label_18.setMaximumSize(QtCore.QSize(200, 20))
        self.label_18.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_5.addWidget(self.label_18, 0, QtCore.Qt.AlignHCenter)
        self.uploaded_files_5 = QtWidgets.QLabel(self.DeflateDecomp)
        self.uploaded_files_5.setMinimumSize(QtCore.QSize(300, 30))
        self.uploaded_files_5.setMaximumSize(QtCore.QSize(300, 50))
        self.uploaded_files_5.setStyleSheet("border-color: rgb(78, 139, 119);\n"
"color: rgb(201, 216, 197);\n"
"border: 1px solid  rgb(78, 139, 119);\n"
"font: 75 9pt \"Inter\";\n"
"border-radius:3px;")
        self.uploaded_files_5.setText("")
        self.uploaded_files_5.setObjectName("uploaded_files_5")
        self.verticalLayout_5.addWidget(self.uploaded_files_5, 0, QtCore.Qt.AlignHCenter)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem27)
        self.button_decompress_2 = QtWidgets.QPushButton(self.DeflateDecomp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_decompress_2.sizePolicy().hasHeightForWidth())
        self.button_decompress_2.setSizePolicy(sizePolicy)
        self.button_decompress_2.setMinimumSize(QtCore.QSize(300, 50))
        self.button_decompress_2.setMaximumSize(QtCore.QSize(300, 50))
        self.button_decompress_2.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.button_decompress_2.setObjectName("button_decompress_2")
        self.verticalLayout_5.addWidget(self.button_decompress_2, 0, QtCore.Qt.AlignHCenter)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem28)
        self.status_5 = QtWidgets.QLabel(self.DeflateDecomp)
        self.status_5.setMinimumSize(QtCore.QSize(300, 30))
        self.status_5.setMaximumSize(QtCore.QSize(300, 30))
        self.status_5.setStyleSheet("color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.status_5.setText("")
        self.status_5.setObjectName("status_5")
        self.verticalLayout_5.addWidget(self.status_5, 0, QtCore.Qt.AlignHCenter)
        self.tabWidget.addTab(self.DeflateDecomp, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setAutoFillBackground(False)
        self.tab_1.setStyleSheet("QTabBar::tab {\n"
"  background: gray;\n"
"  color: white;\n"
"  padding: 10px;\n"
" }\n"
"\n"
" QTabBar::tab:selected {\n"
"  background: lightgray;\n"
" }")
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.status_2 = QtWidgets.QLabel(self.tab_1)
        self.status_2.setMinimumSize(QtCore.QSize(300, 30))
        self.status_2.setMaximumSize(QtCore.QSize(300, 30))
        self.status_2.setStyleSheet("color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.status_2.setText("")
        self.status_2.setObjectName("status_2")
        self.gridLayout_3.addWidget(self.status_2, 9, 1, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem29, 5, 1, 1, 1)
        self.button_compress_2 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_compress_2.sizePolicy().hasHeightForWidth())
        self.button_compress_2.setSizePolicy(sizePolicy)
        self.button_compress_2.setMinimumSize(QtCore.QSize(0, 50))
        self.button_compress_2.setMaximumSize(QtCore.QSize(300, 50))
        self.button_compress_2.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.button_compress_2.setObjectName("button_compress_2")
        self.gridLayout_3.addWidget(self.button_compress_2, 6, 1, 1, 1)
        self.uploaded_files_2 = QtWidgets.QLabel(self.tab_1)
        self.uploaded_files_2.setMinimumSize(QtCore.QSize(0, 30))
        self.uploaded_files_2.setMaximumSize(QtCore.QSize(300, 30))
        self.uploaded_files_2.setStyleSheet("border-color: rgb(78, 139, 119);\n"
"border: 1px solid  rgb(78, 139, 119);\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.uploaded_files_2.setText("")
        self.uploaded_files_2.setScaledContents(False)
        self.uploaded_files_2.setObjectName("uploaded_files_2")
        self.gridLayout_3.addWidget(self.uploaded_files_2, 4, 1, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem30, 7, 1, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem31, 3, 2, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem32, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_1)
        self.label_2.setMaximumSize(QtCore.QSize(300, 30))
        self.label_2.setStyleSheet("\n"
"border-radius:3px;\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 3, 1, 1, 1)
        self.button_files_2 = QtWidgets.QPushButton(self.tab_1)
        self.button_files_2.setEnabled(True)
        self.button_files_2.setMinimumSize(QtCore.QSize(300, 100))
        self.button_files_2.setMaximumSize(QtCore.QSize(300, 100))
        self.button_files_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.button_files_2.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.button_files_2.setObjectName("button_files_2")
        self.gridLayout_3.addWidget(self.button_files_2, 1, 1, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem33, 0, 1, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem34, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem35 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem35, 3, 1, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem36, 6, 1, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem37, 9, 1, 1, 1)
        self.uploaded_files_3 = QtWidgets.QLabel(self.tab)
        self.uploaded_files_3.setMinimumSize(QtCore.QSize(0, 30))
        self.uploaded_files_3.setMaximumSize(QtCore.QSize(300, 30))
        self.uploaded_files_3.setStyleSheet("border-color: rgb(78, 139, 119);\n"
"color: rgb(201, 216, 197);\n"
"border: 1px solid  rgb(78, 139, 119);\n"
"font: 75 9pt \"Inter\";\n"
"border-radius:3px;")
        self.uploaded_files_3.setText("")
        self.uploaded_files_3.setObjectName("uploaded_files_3")
        self.gridLayout_4.addWidget(self.uploaded_files_3, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setMaximumSize(QtCore.QSize(300, 30))
        self.label_5.setStyleSheet("\n"
"color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 4, 1, 1, 1)
        self.button_compress_3 = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_compress_3.sizePolicy().hasHeightForWidth())
        self.button_compress_3.setSizePolicy(sizePolicy)
        self.button_compress_3.setMinimumSize(QtCore.QSize(0, 50))
        self.button_compress_3.setMaximumSize(QtCore.QSize(300, 50))
        self.button_compress_3.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.button_compress_3.setObjectName("button_compress_3")
        self.gridLayout_4.addWidget(self.button_compress_3, 8, 1, 1, 1)
        self.status_3 = QtWidgets.QLabel(self.tab)
        self.status_3.setMinimumSize(QtCore.QSize(300, 30))
        self.status_3.setMaximumSize(QtCore.QSize(300, 30))
        self.status_3.setStyleSheet("color: rgb(201, 216, 197);\n"
"font: 75 9pt \"Inter\";")
        self.status_3.setText("")
        self.status_3.setObjectName("status_3")
        self.gridLayout_4.addWidget(self.status_3, 10, 1, 1, 1)
        self.button_files_3 = QtWidgets.QPushButton(self.tab)
        self.button_files_3.setEnabled(True)
        self.button_files_3.setMinimumSize(QtCore.QSize(300, 100))
        self.button_files_3.setMaximumSize(QtCore.QSize(300, 100))
        self.button_files_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.button_files_3.setStyleSheet("QPushButton {\n"
"color: rgb(201, 216, 197);\n"
"background-color: rgb(70, 83, 66);\n"
"font: 75 16pt \"Inter\";\n"
"border-radius:5px;\n"
"display:inline-block;\n"
"font-weight:bold;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(71, 85, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(52, 62, 49);\n"
"    padding-top: 1 px;\n"
"}")
        self.button_files_3.setObjectName("button_files_3")
        self.gridLayout_4.addWidget(self.button_files_3, 2, 1, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem38, 0, 1, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem39, 5, 0, 1, 1)
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem40, 5, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.HuffmanComp.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.chosenFile.setText(_translate("Dialog", "Выбранный файл:"))
        self.ButtonEnter.setText(_translate("Dialog", "Ввод"))
        self.chooseFile.setText(_translate("Dialog", "Выберите файл"))
        self.label.setText(_translate("Dialog", "Введите текст или выберите файл для сжатия:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.HuffmanComp), _translate("Dialog", "Huffman"))
        self.button_decompress.setText(_translate("Dialog", "Ввод"))
        self.label_4.setText(_translate("Dialog", "Выбранный файл:"))
        self.button_files_4.setText(_translate("Dialog", "Выбрать файл"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Huffman декомпрессия"))
        self.label_7.setText(_translate("Dialog", "Введите текст:"))
        self.label_8.setText(_translate("Dialog", "Параметры"))
        self.label_6.setText(_translate("Dialog", "Размер скользящего окна:"))
        self.label_9.setText(_translate("Dialog", "Буфер"))
        self.pushButton.setText(_translate("Dialog", "Ввод"))
        self.label_13.setText(_translate("Dialog", "Время выполнения сжатия:"))
        self.label_11.setText(_translate("Dialog", "Размер изначального текста:"))
        self.label_10.setText(_translate("Dialog", "Размер сжатого текста:"))
        self.label_12.setText(_translate("Dialog", "Процент сжатия: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "LZ77"))
        self.label_14.setText(_translate("Dialog", "Введите закодированную последовательность:"))
        self.pushButton_2.setText(_translate("Dialog", "Ввод"))
        self.label_17.setText(_translate("Dialog", "Время выполнения декомпрессии:"))
        self.label_16.setText(_translate("Dialog", "Размер входных данных:"))
        self.label_15.setText(_translate("Dialog", "Размер оригинального текста:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.lz77decompression), _translate("Dialog", "LZ77 декомпрессия"))
        self.label_34.setText(_translate("Dialog", "Введите текст или выберите файл для сжатия:"))
        self.chooseFile_3.setText(_translate("Dialog", "Выберите файл"))
        self.chosenFile_3.setText(_translate("Dialog", "Выбранный файл:"))
        self.pushButton_5.setText(_translate("Dialog", "Ввод"))
        self.label_33.setText(_translate("Dialog", "Время выполнения сжатия:"))
        self.label_35.setText(_translate("Dialog", "Размер изначального текста:"))
        self.label_36.setText(_translate("Dialog", "Размер сжатого текста:"))
        self.label_37.setText(_translate("Dialog", "Процент сжатия: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DeflateComp), _translate("Dialog", "Deflate"))
        self.button_files_5.setText(_translate("Dialog", "Выбрать файл"))
        self.label_18.setText(_translate("Dialog", "Выбранный файл:"))
        self.button_decompress_2.setText(_translate("Dialog", "Ввод"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DeflateDecomp), _translate("Dialog", "Deflate декомпрессия"))
        self.button_compress_2.setText(_translate("Dialog", "Сжать"))
        self.label_2.setText(_translate("Dialog", "Выбранные файлы:"))
        self.button_files_2.setText(_translate("Dialog", "Выбрать файл или \n"
"несколько файлов"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Dialog", "архивация в zip"))
        self.label_5.setText(_translate("Dialog", "Выбранный файл:"))
        self.button_compress_3.setText(_translate("Dialog", "Распаковать"))
        self.button_files_3.setText(_translate("Dialog", "Выбрать архив"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "распаковать архив"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
